# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vocabList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for vocabList
     pod 'Firebase/Analytics'
     pod 'Firebase/Database'
     
  target 'vocabListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vocabListUITests' do
    # Pods for testing
  end

end
